name: black-foramtter

on: [push, pull_request, workflow_dispatch]

jobs:
  formatter:
    name: black formatter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Black Formatter Check
        uses: lgeiger/black-action@v1.0.1
        with:
          args: . --config ./pyproject.toml --verbose # --diff --color

      - name: isort Check
        uses: isort/isort-action@master
        with:
          configuration: --settings-path ./pyproject.toml --verbose # --diff

      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)

      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'winterbloooom'
          git config --global user.email 'winterbloooom@gmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Black format change"
          git push